services:
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
      - TZ=America/Phoenix
    ports:
      # Port 8443 removed from here; it's now private to caddy_net
      - "25565:25565/tcp" # JoJo Winds of Reqium
      - "25566:25566/tcp" # AOT Helos
      - "24454:24454/udp" # Voice Chat AOT Helos
      - "24455:24455/udp" # Voice Chat JoJo Winds of Reqium
      - "25500-25600:25500-25600/tcp" # MC Server Range
    volumes:
      - ./docker/backups:/crafty/backups
      - ./docker/logs:/crafty/logs
      - ./docker/servers:/crafty/servers
      - ./docker/config:/crafty/app/config
      - ./docker/import:/crafty/import
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
