services:
  siyuan:
    image: b3log/siyuan:latest
    container_name: siyuan
    hostname: siyuan
    restart: always
    environment:
      - TZ=America/Phoenix
    networks:
      - caddy_net
    volumes:
      - siyuan-workspace:/siyuan/workspace
    command: ["--workspace=/siyuan/workspace", "--accessAuthCode=${SIYUAN_AUTH_CODE:-ChangeMeSiyuan123!}"]

networks:
  caddy_net:
    external: true

volumes:
  siyuan-workspace:
