services:
  linkstack:
    image: linkstackorg/linkstack:latest
    container_name: links
    restart: always
    environment:
      - TZ=America/Phoenix
      - SERVER_ADMIN=khgreenprime@gmail.com
      - HTTP_SERVER_NAME=links.quadstronix.dev
      - HTTPS_SERVER_NAME=links.quadstronix.dev
      - PHP_MEMORY_LIMIT=512M
      - UPLOAD_MAX_FILESIZE=16M
    volumes:
      - ./htdocs:/htdocs
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
