services:
  linkstack:
    image: linkstackorg/linkstack
    container_name: links
    hostname: linkstack
    environment:
      HTTP_SERVER_NAME: "links.quadstronix.dev"
      HTTPS_SERVER_NAME: "links.quadstronix.dev"
      SERVER_ADMIN: "khgreenprime@gmail.com"
      TZ: "America/Phoenix"
      PHP_MEMORY_LIMIT: "512M"
      UPLOAD_MAX_FILESIZE: "8M"
    networks:
      - caddy_net
    restart: always
    volumes:
      - "linkstack:/htdocs"
      - "./entrypoint.sh:/custom-entrypoint.sh:ro"
    entrypoint: ["/bin/sh", "/custom-entrypoint.sh"]
networks:
  caddy_net:
    external: true
volumes:
  linkstack:
